use std::error::Error;
use util::*;
use instruction::*;

pub fn decode_instruction<F>(mut next_byte: F) -> Result<Instruction, Box<Error>>
    where F: FnMut() -> Result<u8, Box<Error>>
{
    fn next_word16<F: FnMut() -> Result<u8, Box<Error>>>(mut next_byte: F)
                                                         -> Result<u16, Box<Error>> {
        let l = next_byte()?;
        let h = next_byte()?;
        Ok(make_word16(h, l))
    }

    match next_byte()? {
        0x7f => Ok(LD_R_R(ARegister, ARegister)),
        0x78 => Ok(LD_R_R(ARegister, BRegister)),
        0x79 => Ok(LD_R_R(ARegister, CRegister)),
        0x7a => Ok(LD_R_R(ARegister, DRegister)),
        0x7b => Ok(LD_R_R(ARegister, ERegister)),
        0x7c => Ok(LD_R_R(ARegister, HRegister)),
        0x7d => Ok(LD_R_R(ARegister, LRegister)),

        0x47 => Ok(LD_R_R(BRegister, ARegister)),
        0x40 => Ok(LD_R_R(BRegister, BRegister)),
        0x41 => Ok(LD_R_R(BRegister, CRegister)),
        0x42 => Ok(LD_R_R(BRegister, DRegister)),
        0x43 => Ok(LD_R_R(BRegister, ERegister)),
        0x44 => Ok(LD_R_R(BRegister, HRegister)),
        0x45 => Ok(LD_R_R(BRegister, LRegister)),

        0x4f => Ok(LD_R_R(CRegister, ARegister)),
        0x48 => Ok(LD_R_R(CRegister, BRegister)),
        0x49 => Ok(LD_R_R(CRegister, CRegister)),
        0x4a => Ok(LD_R_R(CRegister, DRegister)),
        0x4b => Ok(LD_R_R(CRegister, ERegister)),
        0x4c => Ok(LD_R_R(CRegister, HRegister)),
        0x4d => Ok(LD_R_R(CRegister, LRegister)),

        0x57 => Ok(LD_R_R(DRegister, ARegister)),
        0x50 => Ok(LD_R_R(DRegister, BRegister)),
        0x51 => Ok(LD_R_R(DRegister, CRegister)),
        0x52 => Ok(LD_R_R(DRegister, DRegister)),
        0x53 => Ok(LD_R_R(DRegister, ERegister)),
        0x54 => Ok(LD_R_R(DRegister, HRegister)),
        0x55 => Ok(LD_R_R(DRegister, LRegister)),

        0x5f => Ok(LD_R_R(ERegister, ARegister)),
        0x58 => Ok(LD_R_R(ERegister, BRegister)),
        0x59 => Ok(LD_R_R(ERegister, CRegister)),
        0x5a => Ok(LD_R_R(ERegister, DRegister)),
        0x5b => Ok(LD_R_R(ERegister, ERegister)),
        0x5c => Ok(LD_R_R(ERegister, HRegister)),
        0x5d => Ok(LD_R_R(ERegister, LRegister)),

        0x67 => Ok(LD_R_R(HRegister, ARegister)),
        0x60 => Ok(LD_R_R(HRegister, BRegister)),
        0x61 => Ok(LD_R_R(HRegister, CRegister)),
        0x62 => Ok(LD_R_R(HRegister, DRegister)),
        0x63 => Ok(LD_R_R(HRegister, ERegister)),
        0x64 => Ok(LD_R_R(HRegister, HRegister)),
        0x65 => Ok(LD_R_R(HRegister, LRegister)),

        0x6f => Ok(LD_R_R(LRegister, ARegister)),
        0x68 => Ok(LD_R_R(LRegister, BRegister)),
        0x69 => Ok(LD_R_R(LRegister, CRegister)),
        0x6a => Ok(LD_R_R(LRegister, DRegister)),
        0x6b => Ok(LD_R_R(LRegister, ERegister)),
        0x6c => Ok(LD_R_R(LRegister, HRegister)),
        0x6d => Ok(LD_R_R(LRegister, LRegister)),

        0x3e => Ok(LD_R_N(ARegister, next_byte()?)),
        0x06 => Ok(LD_R_N(BRegister, next_byte()?)),
        0x0e => Ok(LD_R_N(CRegister, next_byte()?)),
        0x16 => Ok(LD_R_N(DRegister, next_byte()?)),
        0x1e => Ok(LD_R_N(ERegister, next_byte()?)),
        0x26 => Ok(LD_R_N(HRegister, next_byte()?)),
        0x2e => Ok(LD_R_N(LRegister, next_byte()?)),

        0x7e => Ok(LD_R_ATHL(ARegister)),
        0x46 => Ok(LD_R_ATHL(BRegister)),
        0x4e => Ok(LD_R_ATHL(CRegister)),
        0x56 => Ok(LD_R_ATHL(DRegister)),
        0x5e => Ok(LD_R_ATHL(ERegister)),
        0x66 => Ok(LD_R_ATHL(HRegister)),
        0x6e => Ok(LD_R_ATHL(LRegister)),

        0x77 => Ok(LD_ATHL_R(ARegister)),
        0x70 => Ok(LD_ATHL_R(BRegister)),
        0x71 => Ok(LD_ATHL_R(CRegister)),
        0x72 => Ok(LD_ATHL_R(DRegister)),
        0x73 => Ok(LD_ATHL_R(ERegister)),
        0x74 => Ok(LD_ATHL_R(HRegister)),
        0x75 => Ok(LD_ATHL_R(LRegister)),

        0x36 => Ok(LD_ATHL_N(next_byte()?)),

        0xf2 => Ok(LD_A_ATC),
        0x0a => Ok(LD_A_ATBC),
        0x1a => Ok(LD_A_ATDE),
        0xfa => Ok(LD_A_ATNN(next_word16(next_byte)?)),

        0xe2 => Ok(LD_ATC_A),
        0x02 => Ok(LD_ATBC_A),
        0x12 => Ok(LD_ATDE_A),
        0xea => Ok(LD_ATNN_A(next_word16(next_byte)?)),

        0x3a => Ok(LDD_A_ATHL),
        0x32 => Ok(LDD_ATHL_A),

        0x2a => Ok(LDI_A_ATHL),
        0x22 => Ok(LDI_ATHL_A),

        0xf0 => Ok(LDH_A_ATN(next_byte()?)),
        0xe0 => Ok(LDH_ATN_A(next_byte()?)),

        0x01 => Ok(LD_BC_NN(next_word16(next_byte)?)),
        0x11 => Ok(LD_DE_NN(next_word16(next_byte)?)),
        0x21 => Ok(LD_HL_NN(next_word16(next_byte)?)),
        0x31 => Ok(LD_SP_NN(next_word16(next_byte)?)),

        0xf9 => Ok(LD_SP_HL),
        0xf8 => Ok(LDHL_SP_N(next_byte()? as i8)),
        0x08 => Ok(LD_ATNN_SP(next_word16(next_byte)?)),

        0xf5 => Ok(PUSH_AF),
        0xc5 => Ok(PUSH_BC),
        0xd5 => Ok(PUSH_DE),
        0xe5 => Ok(PUSH_HL),

        0xf1 => Ok(POP_AF),
        0xc1 => Ok(POP_BC),
        0xd1 => Ok(POP_DE),
        0xe1 => Ok(POP_HL),

        0x87 => Ok(ADD_A_R(ARegister)),
        0x80 => Ok(ADD_A_R(BRegister)),
        0x81 => Ok(ADD_A_R(CRegister)),
        0x82 => Ok(ADD_A_R(DRegister)),
        0x83 => Ok(ADD_A_R(ERegister)),
        0x84 => Ok(ADD_A_R(HRegister)),
        0x85 => Ok(ADD_A_R(LRegister)),
        0xc6 => Ok(ADD_A_N(next_byte()?)),
        0x86 => Ok(ADD_A_ATHL),

        0x8f => Ok(ADC_A_R(ARegister)),
        0x88 => Ok(ADC_A_R(BRegister)),
        0x89 => Ok(ADC_A_R(CRegister)),
        0x8a => Ok(ADC_A_R(DRegister)),
        0x8b => Ok(ADC_A_R(ERegister)),
        0x8c => Ok(ADC_A_R(HRegister)),
        0x8d => Ok(ADC_A_R(LRegister)),
        0xce => Ok(ADC_A_N(next_byte()?)),
        0x8e => Ok(ADC_A_ATHL),

        0x97 => Ok(SUB_R(ARegister)),
        0x90 => Ok(SUB_R(BRegister)),
        0x91 => Ok(SUB_R(CRegister)),
        0x92 => Ok(SUB_R(DRegister)),
        0x93 => Ok(SUB_R(ERegister)),
        0x94 => Ok(SUB_R(HRegister)),
        0x95 => Ok(SUB_R(LRegister)),
        0xd6 => Ok(SUB_N(next_byte()?)),
        0x96 => Ok(SUB_ATHL),

        0x9f => Ok(SBC_A_R(ARegister)),
        0x98 => Ok(SBC_A_R(BRegister)),
        0x99 => Ok(SBC_A_R(CRegister)),
        0x9a => Ok(SBC_A_R(DRegister)),
        0x9b => Ok(SBC_A_R(ERegister)),
        0x9c => Ok(SBC_A_R(HRegister)),
        0x9d => Ok(SBC_A_R(LRegister)),
        0xde => Ok(SBC_A_N(next_byte()?)),
        0x9e => Ok(SBC_A_ATHL),

        0xa7 => Ok(AND_R(ARegister)),
        0xa0 => Ok(AND_R(BRegister)),
        0xa1 => Ok(AND_R(CRegister)),
        0xa2 => Ok(AND_R(DRegister)),
        0xa3 => Ok(AND_R(ERegister)),
        0xa4 => Ok(AND_R(HRegister)),
        0xa5 => Ok(AND_R(LRegister)),
        0xe6 => Ok(AND_N(next_byte()?)),
        0xa6 => Ok(AND_ATHL),

        0xb7 => Ok(OR_R(ARegister)),
        0xb0 => Ok(OR_R(BRegister)),
        0xb1 => Ok(OR_R(CRegister)),
        0xb2 => Ok(OR_R(DRegister)),
        0xb3 => Ok(OR_R(ERegister)),
        0xb4 => Ok(OR_R(HRegister)),
        0xb5 => Ok(OR_R(LRegister)),
        0xf6 => Ok(OR_N(next_byte()?)),
        0xb6 => Ok(OR_ATHL),

        0xaf => Ok(XOR_R(ARegister)),
        0xa8 => Ok(XOR_R(BRegister)),
        0xa9 => Ok(XOR_R(CRegister)),
        0xaa => Ok(XOR_R(DRegister)),
        0xab => Ok(XOR_R(ERegister)),
        0xac => Ok(XOR_R(HRegister)),
        0xad => Ok(XOR_R(LRegister)),
        0xee => Ok(XOR_N(next_byte()?)),
        0xae => Ok(XOR_ATHL),

        0xbf => Ok(CP_R(ARegister)),
        0xb8 => Ok(CP_R(BRegister)),
        0xb9 => Ok(CP_R(CRegister)),
        0xba => Ok(CP_R(DRegister)),
        0xbb => Ok(CP_R(ERegister)),
        0xbc => Ok(CP_R(HRegister)),
        0xbd => Ok(CP_R(LRegister)),
        0xfe => Ok(CP_N(next_byte()?)),
        0xbe => Ok(CP_ATHL),

        0x3c => Ok(INC_R(ARegister)),
        0x04 => Ok(INC_R(BRegister)),
        0x0c => Ok(INC_R(CRegister)),
        0x14 => Ok(INC_R(DRegister)),
        0x1c => Ok(INC_R(ERegister)),
        0x24 => Ok(INC_R(HRegister)),
        0x2c => Ok(INC_R(LRegister)),
        0x34 => Ok(INC_ATHL),

        0x3d => Ok(DEC_R(ARegister)),
        0x05 => Ok(DEC_R(BRegister)),
        0x0d => Ok(DEC_R(CRegister)),
        0x15 => Ok(DEC_R(DRegister)),
        0x1d => Ok(DEC_R(ERegister)),
        0x25 => Ok(DEC_R(HRegister)),
        0x2d => Ok(DEC_R(LRegister)),
        0x35 => Ok(DEC_ATHL),

        0x09 => Ok(ADD_HL_BC),
        0x19 => Ok(ADD_HL_DE),
        0x29 => Ok(ADD_HL_HL),
        0x39 => Ok(ADD_HL_SP),

        0xe8 => Ok(ADD_SP_N(next_byte()? as i8)),

        0x03 => Ok(INC_BC),
        0x13 => Ok(INC_DE),
        0x23 => Ok(INC_HL),
        0x33 => Ok(INC_SP),

        0x0b => Ok(DEC_BC),
        0x1b => Ok(DEC_DE),
        0x2b => Ok(DEC_HL),
        0x3b => Ok(DEC_SP),

        0x27 => Ok(DAA),
        0x2f => Ok(CPL),
        0x3f => Ok(CCF),
        0x37 => Ok(SCF),

        0x00 => Ok(NOP),
        0x76 => Ok(HALT),

        0xf3 => Ok(DI),
        0xfb => Ok(EI),

        0x07 => Ok(RLCA),
        0x17 => Ok(RLA),
        0x0f => Ok(RRCA),
        0x1f => Ok(RRA),

        0xc3 => Ok(JP_NN(next_word16(next_byte)?)),
        0xc2 => Ok(JP_C_NN(NZero, next_word16(next_byte)?)),
        0xca => Ok(JP_C_NN(Zero, next_word16(next_byte)?)),
        0xd2 => Ok(JP_C_NN(NCarry, next_word16(next_byte)?)),
        0xda => Ok(JP_C_NN(Carry, next_word16(next_byte)?)),
        0xe9 => Ok(JP_ATHL),

        0x18 => Ok(JR_N(next_byte()? as i8)),
        0x20 => Ok(JR_C_N(NZero, next_byte()? as i8)),
        0x28 => Ok(JR_C_N(Zero, next_byte()? as i8)),
        0x30 => Ok(JR_C_N(NCarry, next_byte()? as i8)),
        0x38 => Ok(JR_C_N(Carry, next_byte()? as i8)),

        0xcd => Ok(CALL_NN(next_word16(next_byte)?)),
        0xc4 => Ok(CALL_C_NN(NZero, next_word16(next_byte)?)),
        0xcc => Ok(CALL_C_NN(Zero, next_word16(next_byte)?)),
        0xd4 => Ok(CALL_C_NN(NCarry, next_word16(next_byte)?)),
        0xdc => Ok(CALL_C_NN(Carry, next_word16(next_byte)?)),

        0xc7 => Ok(RST_RA(Reset00)),
        0xcf => Ok(RST_RA(Reset08)),
        0xd7 => Ok(RST_RA(Reset10)),
        0xdf => Ok(RST_RA(Reset18)),
        0xe7 => Ok(RST_RA(Reset20)),
        0xef => Ok(RST_RA(Reset28)),
        0xf7 => Ok(RST_RA(Reset30)),
        0xff => Ok(RST_RA(Reset38)),

        0xc9 => Ok(RET),
        0xc0 => Ok(RET_C(NZero)),
        0xc8 => Ok(RET_C(Zero)),
        0xd0 => Ok(RET_C(NCarry)),
        0xd8 => Ok(RET_C(Carry)),

        0xd9 => Ok(RETI),

        0x10 => {
            match next_byte()? {
                0x00 => Ok(STOP),
                b => Err(format!("Improper instruction byte {:x} following 0x10", b).into()),
            }
        }

        0xcb => {
            match next_byte()? {
                0x37 => Ok(SWAP_R(ARegister)),
                0x30 => Ok(SWAP_R(BRegister)),
                0x31 => Ok(SWAP_R(CRegister)),
                0x32 => Ok(SWAP_R(DRegister)),
                0x33 => Ok(SWAP_R(ERegister)),
                0x34 => Ok(SWAP_R(HRegister)),
                0x35 => Ok(SWAP_R(LRegister)),
                0x36 => Ok(SWAP_ATHL),

                0x07 => Ok(RLC_R(ARegister)),
                0x00 => Ok(RLC_R(BRegister)),
                0x01 => Ok(RLC_R(CRegister)),
                0x02 => Ok(RLC_R(DRegister)),
                0x03 => Ok(RLC_R(ERegister)),
                0x04 => Ok(RLC_R(HRegister)),
                0x05 => Ok(RLC_R(LRegister)),
                0x06 => Ok(RLC_ATHL),

                0x17 => Ok(RL_R(ARegister)),
                0x10 => Ok(RL_R(BRegister)),
                0x11 => Ok(RL_R(CRegister)),
                0x12 => Ok(RL_R(DRegister)),
                0x13 => Ok(RL_R(ERegister)),
                0x14 => Ok(RL_R(HRegister)),
                0x15 => Ok(RL_R(LRegister)),
                0x16 => Ok(RL_ATHL),

                0x0f => Ok(RRC_R(ARegister)),
                0x08 => Ok(RRC_R(BRegister)),
                0x09 => Ok(RRC_R(CRegister)),
                0x0a => Ok(RRC_R(DRegister)),
                0x0b => Ok(RRC_R(ERegister)),
                0x0c => Ok(RRC_R(HRegister)),
                0x0d => Ok(RRC_R(LRegister)),
                0x0e => Ok(RRC_ATHL),

                0x1f => Ok(RR_R(ARegister)),
                0x18 => Ok(RR_R(BRegister)),
                0x19 => Ok(RR_R(CRegister)),
                0x1a => Ok(RR_R(DRegister)),
                0x1b => Ok(RR_R(ERegister)),
                0x1c => Ok(RR_R(HRegister)),
                0x1d => Ok(RR_R(LRegister)),
                0x1e => Ok(RR_ATHL),

                0x27 => Ok(SLA_R(ARegister)),
                0x20 => Ok(SLA_R(BRegister)),
                0x21 => Ok(SLA_R(CRegister)),
                0x22 => Ok(SLA_R(DRegister)),
                0x23 => Ok(SLA_R(ERegister)),
                0x24 => Ok(SLA_R(HRegister)),
                0x25 => Ok(SLA_R(LRegister)),
                0x26 => Ok(SLA_ATHL),

                0x2f => Ok(SRA_R(ARegister)),
                0x28 => Ok(SRA_R(BRegister)),
                0x29 => Ok(SRA_R(CRegister)),
                0x2a => Ok(SRA_R(DRegister)),
                0x2b => Ok(SRA_R(ERegister)),
                0x2c => Ok(SRA_R(HRegister)),
                0x2d => Ok(SRA_R(LRegister)),
                0x2e => Ok(SRA_ATHL),

                0x3f => Ok(SRL_R(ARegister)),
                0x38 => Ok(SRL_R(BRegister)),
                0x39 => Ok(SRL_R(CRegister)),
                0x3a => Ok(SRL_R(DRegister)),
                0x3b => Ok(SRL_R(ERegister)),
                0x3c => Ok(SRL_R(HRegister)),
                0x3d => Ok(SRL_R(LRegister)),
                0x3e => Ok(SRL_ATHL),

                0x47 => Ok(BIT_B_R(Bit0, ARegister)),
                0x40 => Ok(BIT_B_R(Bit0, BRegister)),
                0x41 => Ok(BIT_B_R(Bit0, CRegister)),
                0x42 => Ok(BIT_B_R(Bit0, DRegister)),
                0x43 => Ok(BIT_B_R(Bit0, ERegister)),
                0x44 => Ok(BIT_B_R(Bit0, HRegister)),
                0x45 => Ok(BIT_B_R(Bit0, LRegister)),
                0x46 => Ok(BIT_B_ATHL(Bit0)),

                0x4f => Ok(BIT_B_R(Bit1, ARegister)),
                0x48 => Ok(BIT_B_R(Bit1, BRegister)),
                0x49 => Ok(BIT_B_R(Bit1, CRegister)),
                0x4a => Ok(BIT_B_R(Bit1, DRegister)),
                0x4b => Ok(BIT_B_R(Bit1, ERegister)),
                0x4c => Ok(BIT_B_R(Bit1, HRegister)),
                0x4d => Ok(BIT_B_R(Bit1, LRegister)),
                0x4e => Ok(BIT_B_ATHL(Bit1)),

                0x57 => Ok(BIT_B_R(Bit2, ARegister)),
                0x50 => Ok(BIT_B_R(Bit2, BRegister)),
                0x51 => Ok(BIT_B_R(Bit2, CRegister)),
                0x52 => Ok(BIT_B_R(Bit2, DRegister)),
                0x53 => Ok(BIT_B_R(Bit2, ERegister)),
                0x54 => Ok(BIT_B_R(Bit2, HRegister)),
                0x55 => Ok(BIT_B_R(Bit2, LRegister)),
                0x56 => Ok(BIT_B_ATHL(Bit2)),

                0x5f => Ok(BIT_B_R(Bit3, ARegister)),
                0x58 => Ok(BIT_B_R(Bit3, BRegister)),
                0x59 => Ok(BIT_B_R(Bit3, CRegister)),
                0x5a => Ok(BIT_B_R(Bit3, DRegister)),
                0x5b => Ok(BIT_B_R(Bit3, ERegister)),
                0x5c => Ok(BIT_B_R(Bit3, HRegister)),
                0x5d => Ok(BIT_B_R(Bit3, LRegister)),
                0x5e => Ok(BIT_B_ATHL(Bit3)),

                0x67 => Ok(BIT_B_R(Bit4, ARegister)),
                0x60 => Ok(BIT_B_R(Bit4, BRegister)),
                0x61 => Ok(BIT_B_R(Bit4, CRegister)),
                0x62 => Ok(BIT_B_R(Bit4, DRegister)),
                0x63 => Ok(BIT_B_R(Bit4, ERegister)),
                0x64 => Ok(BIT_B_R(Bit4, HRegister)),
                0x65 => Ok(BIT_B_R(Bit4, LRegister)),
                0x66 => Ok(BIT_B_ATHL(Bit4)),

                0x6f => Ok(BIT_B_R(Bit5, ARegister)),
                0x68 => Ok(BIT_B_R(Bit5, BRegister)),
                0x69 => Ok(BIT_B_R(Bit5, CRegister)),
                0x6a => Ok(BIT_B_R(Bit5, DRegister)),
                0x6b => Ok(BIT_B_R(Bit5, ERegister)),
                0x6c => Ok(BIT_B_R(Bit5, HRegister)),
                0x6d => Ok(BIT_B_R(Bit5, LRegister)),
                0x6e => Ok(BIT_B_ATHL(Bit5)),

                0x77 => Ok(BIT_B_R(Bit6, ARegister)),
                0x70 => Ok(BIT_B_R(Bit6, BRegister)),
                0x71 => Ok(BIT_B_R(Bit6, CRegister)),
                0x72 => Ok(BIT_B_R(Bit6, DRegister)),
                0x73 => Ok(BIT_B_R(Bit6, ERegister)),
                0x74 => Ok(BIT_B_R(Bit6, HRegister)),
                0x75 => Ok(BIT_B_R(Bit6, LRegister)),
                0x76 => Ok(BIT_B_ATHL(Bit6)),

                0x7f => Ok(BIT_B_R(Bit7, ARegister)),
                0x78 => Ok(BIT_B_R(Bit7, BRegister)),
                0x79 => Ok(BIT_B_R(Bit7, CRegister)),
                0x7a => Ok(BIT_B_R(Bit7, DRegister)),
                0x7b => Ok(BIT_B_R(Bit7, ERegister)),
                0x7c => Ok(BIT_B_R(Bit7, HRegister)),
                0x7d => Ok(BIT_B_R(Bit7, LRegister)),
                0x7e => Ok(BIT_B_ATHL(Bit7)),

                0xc7 => Ok(SET_B_R(Bit0, ARegister)),
                0xc0 => Ok(SET_B_R(Bit0, BRegister)),
                0xc1 => Ok(SET_B_R(Bit0, CRegister)),
                0xc2 => Ok(SET_B_R(Bit0, DRegister)),
                0xc3 => Ok(SET_B_R(Bit0, ERegister)),
                0xc4 => Ok(SET_B_R(Bit0, HRegister)),
                0xc5 => Ok(SET_B_R(Bit0, LRegister)),
                0xc6 => Ok(SET_B_ATHL(Bit0)),

                0xcf => Ok(SET_B_R(Bit1, ARegister)),
                0xc8 => Ok(SET_B_R(Bit1, BRegister)),
                0xc9 => Ok(SET_B_R(Bit1, CRegister)),
                0xca => Ok(SET_B_R(Bit1, DRegister)),
                0xcb => Ok(SET_B_R(Bit1, ERegister)),
                0xcc => Ok(SET_B_R(Bit1, HRegister)),
                0xcd => Ok(SET_B_R(Bit1, LRegister)),
                0xce => Ok(SET_B_ATHL(Bit1)),

                0xd7 => Ok(SET_B_R(Bit2, ARegister)),
                0xd0 => Ok(SET_B_R(Bit2, BRegister)),
                0xd1 => Ok(SET_B_R(Bit2, CRegister)),
                0xd2 => Ok(SET_B_R(Bit2, DRegister)),
                0xd3 => Ok(SET_B_R(Bit2, ERegister)),
                0xd4 => Ok(SET_B_R(Bit2, HRegister)),
                0xd5 => Ok(SET_B_R(Bit2, LRegister)),
                0xd6 => Ok(SET_B_ATHL(Bit2)),

                0xdf => Ok(SET_B_R(Bit3, ARegister)),
                0xd8 => Ok(SET_B_R(Bit3, BRegister)),
                0xd9 => Ok(SET_B_R(Bit3, CRegister)),
                0xda => Ok(SET_B_R(Bit3, DRegister)),
                0xdb => Ok(SET_B_R(Bit3, ERegister)),
                0xdc => Ok(SET_B_R(Bit3, HRegister)),
                0xdd => Ok(SET_B_R(Bit3, LRegister)),
                0xde => Ok(SET_B_ATHL(Bit3)),

                0xe7 => Ok(SET_B_R(Bit4, ARegister)),
                0xe0 => Ok(SET_B_R(Bit4, BRegister)),
                0xe1 => Ok(SET_B_R(Bit4, CRegister)),
                0xe2 => Ok(SET_B_R(Bit4, DRegister)),
                0xe3 => Ok(SET_B_R(Bit4, ERegister)),
                0xe4 => Ok(SET_B_R(Bit4, HRegister)),
                0xe5 => Ok(SET_B_R(Bit4, LRegister)),
                0xe6 => Ok(SET_B_ATHL(Bit4)),

                0xef => Ok(SET_B_R(Bit5, ARegister)),
                0xe8 => Ok(SET_B_R(Bit5, BRegister)),
                0xe9 => Ok(SET_B_R(Bit5, CRegister)),
                0xea => Ok(SET_B_R(Bit5, DRegister)),
                0xeb => Ok(SET_B_R(Bit5, ERegister)),
                0xec => Ok(SET_B_R(Bit5, HRegister)),
                0xed => Ok(SET_B_R(Bit5, LRegister)),
                0xee => Ok(SET_B_ATHL(Bit5)),

                0xf7 => Ok(SET_B_R(Bit6, ARegister)),
                0xf0 => Ok(SET_B_R(Bit6, BRegister)),
                0xf1 => Ok(SET_B_R(Bit6, CRegister)),
                0xf2 => Ok(SET_B_R(Bit6, DRegister)),
                0xf3 => Ok(SET_B_R(Bit6, ERegister)),
                0xf4 => Ok(SET_B_R(Bit6, HRegister)),
                0xf5 => Ok(SET_B_R(Bit6, LRegister)),
                0xf6 => Ok(SET_B_ATHL(Bit6)),

                0xff => Ok(SET_B_R(Bit7, ARegister)),
                0xf8 => Ok(SET_B_R(Bit7, BRegister)),
                0xf9 => Ok(SET_B_R(Bit7, CRegister)),
                0xfa => Ok(SET_B_R(Bit7, DRegister)),
                0xfb => Ok(SET_B_R(Bit7, ERegister)),
                0xfc => Ok(SET_B_R(Bit7, HRegister)),
                0xfd => Ok(SET_B_R(Bit7, LRegister)),
                0xfe => Ok(SET_B_ATHL(Bit7)),

                0x87 => Ok(RES_B_R(Bit0, ARegister)),
                0x80 => Ok(RES_B_R(Bit0, BRegister)),
                0x81 => Ok(RES_B_R(Bit0, CRegister)),
                0x82 => Ok(RES_B_R(Bit0, DRegister)),
                0x83 => Ok(RES_B_R(Bit0, ERegister)),
                0x84 => Ok(RES_B_R(Bit0, HRegister)),
                0x85 => Ok(RES_B_R(Bit0, LRegister)),
                0x86 => Ok(RES_B_ATHL(Bit0)),

                0x8f => Ok(RES_B_R(Bit1, ARegister)),
                0x88 => Ok(RES_B_R(Bit1, BRegister)),
                0x89 => Ok(RES_B_R(Bit1, CRegister)),
                0x8a => Ok(RES_B_R(Bit1, DRegister)),
                0x8b => Ok(RES_B_R(Bit1, ERegister)),
                0x8c => Ok(RES_B_R(Bit1, HRegister)),
                0x8d => Ok(RES_B_R(Bit1, LRegister)),
                0x8e => Ok(RES_B_ATHL(Bit1)),

                0x97 => Ok(RES_B_R(Bit2, ARegister)),
                0x90 => Ok(RES_B_R(Bit2, BRegister)),
                0x91 => Ok(RES_B_R(Bit2, CRegister)),
                0x92 => Ok(RES_B_R(Bit2, DRegister)),
                0x93 => Ok(RES_B_R(Bit2, ERegister)),
                0x94 => Ok(RES_B_R(Bit2, HRegister)),
                0x95 => Ok(RES_B_R(Bit2, LRegister)),
                0x96 => Ok(RES_B_ATHL(Bit2)),

                0x9f => Ok(RES_B_R(Bit3, ARegister)),
                0x98 => Ok(RES_B_R(Bit3, BRegister)),
                0x99 => Ok(RES_B_R(Bit3, CRegister)),
                0x9a => Ok(RES_B_R(Bit3, DRegister)),
                0x9b => Ok(RES_B_R(Bit3, ERegister)),
                0x9c => Ok(RES_B_R(Bit3, HRegister)),
                0x9d => Ok(RES_B_R(Bit3, LRegister)),
                0x9e => Ok(RES_B_ATHL(Bit3)),

                0xa7 => Ok(RES_B_R(Bit4, ARegister)),
                0xa0 => Ok(RES_B_R(Bit4, BRegister)),
                0xa1 => Ok(RES_B_R(Bit4, CRegister)),
                0xa2 => Ok(RES_B_R(Bit4, DRegister)),
                0xa3 => Ok(RES_B_R(Bit4, ERegister)),
                0xa4 => Ok(RES_B_R(Bit4, HRegister)),
                0xa5 => Ok(RES_B_R(Bit4, LRegister)),
                0xa6 => Ok(RES_B_ATHL(Bit4)),

                0xaf => Ok(RES_B_R(Bit5, ARegister)),
                0xa8 => Ok(RES_B_R(Bit5, BRegister)),
                0xa9 => Ok(RES_B_R(Bit5, CRegister)),
                0xaa => Ok(RES_B_R(Bit5, DRegister)),
                0xab => Ok(RES_B_R(Bit5, ERegister)),
                0xac => Ok(RES_B_R(Bit5, HRegister)),
                0xad => Ok(RES_B_R(Bit5, LRegister)),
                0xae => Ok(RES_B_ATHL(Bit5)),

                0xb7 => Ok(RES_B_R(Bit6, ARegister)),
                0xb0 => Ok(RES_B_R(Bit6, BRegister)),
                0xb1 => Ok(RES_B_R(Bit6, CRegister)),
                0xb2 => Ok(RES_B_R(Bit6, DRegister)),
                0xb3 => Ok(RES_B_R(Bit6, ERegister)),
                0xb4 => Ok(RES_B_R(Bit6, HRegister)),
                0xb5 => Ok(RES_B_R(Bit6, LRegister)),
                0xb6 => Ok(RES_B_ATHL(Bit6)),

                0xbf => Ok(RES_B_R(Bit7, ARegister)),
                0xb8 => Ok(RES_B_R(Bit7, BRegister)),
                0xb9 => Ok(RES_B_R(Bit7, CRegister)),
                0xba => Ok(RES_B_R(Bit7, DRegister)),
                0xbb => Ok(RES_B_R(Bit7, ERegister)),
                0xbc => Ok(RES_B_R(Bit7, HRegister)),
                0xbd => Ok(RES_B_R(Bit7, LRegister)),
                0xbe => Ok(RES_B_ATHL(Bit7)),

                b => Err(format!("Improper instruction byte {:x} following 0xcb", b).into()),
            }
        }

        b => Err(format!("Improper first byte of instruction {:x}", b).into()),
    }
}
